### ISSUE TITLE
Chrome only shows Vector theme with a single column for all content

### ISSUE THREAD

**Issue by AlJohnson** [OSAS/strapping-mediawiki#16] opened 2013-03-18 23:39 UTC
It looks very much like the "Printable version" page.  

WikiMedia v1.20.2
PHP v5.4.9

Test server: http://ec2-50-112-91-143.us-west-2.compute.amazonaws.com/wiki/index.php/Main_Page

Thanks,
Al

**Comment by garrett** [comment] 2013-03-19 11:19
That's not the vector theme.

I just opened it in Chrome, however, and it appears the CSS isn't loading for some reason. Very odd... Chrome does load the proper CSS in my test instance, so I do know it _should_ be working. (This makes it a little harder for me to figure out what the problem is and how to test a fix.)

I'll still look at it on your site.

**Comment by garrett** [comment] 2013-03-19 11:22
I'm using:

MediaWiki 1.18.2, it appears...
PHP 5.4.12

Perhaps something odd changed on the way to 1.20.2? I'll look into upgrading to 1.20.3 (the latest version now) today.

**Comment by garrett** [comment] 2013-03-19 11:23
Thanks for filing this issue, btw!

**Comment by garrett** [comment] 2013-03-19 11:46
Oops. I'm actually using 1.20.3 on my instance. I'll still try to check into this today.

**Comment by waldyrious** [comment] 2013-03-19 12:35
Interestingly, for me it works correctly in Firefox but not in Chrome (no css). It seems like the css urls are having the &s escaped as &amp; and that breaks the link.

**Comment by garrett** [comment] 2013-03-19 13:03
I'm pretty sure escaped &s should not break links. Browsers usually display an unescaped version in many (but not all) areas. I do see the content for URLs in Chrome.

**Comment by garrett** [comment] 2013-03-19 13:20
It looks like you're using a minifier. What happens when you don't use a minifier?

**Comment by garrett** [comment] 2013-03-19 13:24
I've encountered odd problems with some minifiers before. In general, unless you're Google or Facebook, stripping out whitespace in CSS doesn't really give much savings. Compressing with gzip has much better gains, and it does a very good job at compressing whitespace (unless tabs and spaces are mixed everywhere).

It might be possible that Chrome just doesn't like something that the CSS compression script is doing.

Which minifier are you using?

**Comment by garrett** [comment] 2013-03-19 13:37
Including stylesheets via <link> in the HTML would be better than @import in the CSS for this reason. It's also a little optimization too. We should probably consider doing this (although it should be another issue). 

It would be ideal for minifiers too, as I see @imports are not handled in the example site.

**Comment by waldyrious** [comment] 2013-03-19 18:09
> I'm pretty sure escaped &s should not break links. Browsers usually display an unescaped version in many (but not all) areas.

In the code I see:
&lt;link rel="stylesheet" href="http://ec2-50-112-91-143.us-west-2.compute.amazonaws.com/wiki/load.php?debug=false&amp;lang=en&amp;modules=mediawiki.legacy.commonPrint%2Cshared%7Cskins.strapping&amp;only=styles&amp;skin=strapping&amp;*" />

Following that link results in a page with

```
/* No modules requested. Max made me put this here */
```

If the URL is decoded, as in:
http://ec2-50-112-91-143.us-west-2.compute.amazonaws.com/wiki/load.php?debug=false&lang=en&modules=mediawiki.legacy.commonPrint,shared|skins.strapping&only=styles&skin=strapping&*
...then the contents of the stylesheets are displayed.

This happens in both Chrome and Firefox if following the links directly, but somehow when loading the page, Firefox is able to resolve the address correctly, while Chrome isn't.

**Comment by waldyrious** [comment] 2013-03-19 18:10
There is also
&lt;script src="http://ec2-50-112-91-143.us-west-2.compute.amazonaws.com/wiki/load.php?debug=false&amp;lang=en&amp;modules=startup&amp;only=scripts&amp;skin=strapping&amp;*" >&lt;/script>

which, when decoded, yields
http://ec2-50-112-91-143.us-west-2.compute.amazonaws.com/wiki/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=strapping&*

(same issue as above, but for Javascript this time)

**Comment by waldyrious** [comment] 2013-03-19 18:13
It looks like this has something to do with the [ResourceLoader](http://www.mediawiki.org/wiki/ResourceLoader). Maybe @ryan-lane will have relevant input.

**Comment by ryan-lane** [comment] 2013-03-19 18:17
Hm. I remember seeing this on wiki.openstack.org. Is the CSS broken in any way? Webkit browsers are pretty strict and will just crap out if the CSS is broken in a number of ways.

**Comment by garrett** [comment] 2013-03-19 19:09
I'll check the CSS in the morning (about to step away from the computer for the night). However, Chrome works fine in my dev environment, except for responsive mode. (Perhaps it's related somehow? *shrug*)

**Comment by waldyrious** [comment] 2013-03-20 03:35
@ryan-lane, the output

```
/* No modules requested. Max made me put this here */
```

suggests that it's RL not reading the URL parameters (modules=mediawiki.legacy.commonPrint,shared|skins.strapping) rather than Chrome not accepting its CSS. That's why I'm assuming Chrome isn't processing the URL itself as it should (or Firefox is being too lenient with malformed URLs).

**Comment by garrett** [comment] 2013-03-20 11:41
The CSS for external video icons (introduced in 54a0603eda0edab50a6e9d5268b880abbe1f217a) was not complete in the file. I'm not sure if there should be more icons, but I did complete it based on the pattern from external icons above.

Please pull and try again; hopefully this fixes the CSS related error and makes Chrome happy.

(We may still have the URL issue too. At least the CSS is fixed now though.)

**Comment by AlJohnson** [comment] 2013-03-21 21:12
This checks good!  Except, there was a message in place of the top toolbar that said: 

Notice: Undefined variable: wgGroupPermissions in /usr/local/apache2/htdocs/wiki/skins/strapping/Strapping.skin.php on line 129

So, I just added the global declaration here and the message went away and the toolbar appeared:

<?php global $wgGroupPermissions; if ( $wgGroupPermissions['*']['edit'] || $wgStrappingSkinAnonNavbar || $this->data['loggedin'] ) { ?>

Thanks!

**Comment by garrett** [comment] 2013-03-22 11:45
Oops. Making a fix for that right now.

(Also turning on debug so I can easily spot these issues. Should've done that earlier...)

**Comment by garrett** [comment] 2013-03-22 11:48
Thanks for pointing out the error. I added the global to the top of the function.

> This checks good!

:+1: Okay, closing this bug then. Feel free to reopen if necessary.

**Closed as completed by garrett** 2013-03-22 11:48 UTC
