### ISSUE TITLE
Cant create new articles using search option

### ISSUE THREAD

**Issue by mestrap** [OSAS/strapping-mediawiki#32] opened 2013-06-05 11:26 UTC
Using strapping skin we cant create new articles using search option. When using search this skin is giving this result

"There were no results matching the query."

But when using a Vector Skin search option gives this also
"There were no results matching the query."
"Create the page "Test" on this wiki!"

Where Test is the new article.

Please resolve this bug and thanks for this wonderful skin

**Comment by waldyrious** [comment] 2013-06-06 11:55
This is a duplicate of #26

**Comment by garrett** [comment] 2013-06-12 09:14
Closing as a duplicate.

I'm back from vacation and updating sites, so I'll look into getting this fixed in the next few days.

**Comment by garrett** [comment] 2013-06-12 09:19
On second thought, this is a different (yet related) issue. The other one is a means to create a page in a generic sense (which is actually there, if one has the privileges to do so); this is specifically about creating a page from a search.

**Comment by garrett** [comment] 2013-06-12 10:32
Fixed! Thanks for reporting this issue.

**Closed as completed by garrett** 2013-06-12 10:32 UTC
