### ISSUE TITLE
Navbar drop-downs (Page, Toolbox, user, etc.) don't drop down

### ISSUE THREAD

**Issue by AlJohnson** [OSAS/strapping-mediawiki#7] opened 2013-02-10 09:40 UTC
First, great job on this skin!

But, none of the drop-downs in the navbar work on Firefox or Chrome.  This means you can't even logout.  I followed the readme instructions.  Let me know if you need more info.

MediaWiki 1.20.2

Thanks,
Al

**Comment by Arcane21** [comment] 2013-02-10 22:48
Same problems here. I also get some weird rendering errors trying to display tabs, constantly get messages some lines in the Strapping.php file are misconfigured.

I'm using MediaWiki 1.19.3

**Comment by AlJohnson** [comment] 2013-02-11 00:21
I got those Notices also.  I had to disable their logging in php.ini.

**Comment by waldyrious** [comment] 2013-02-11 00:54
Are the notices related to #2 ?

**Comment by AlJohnson** [comment] 2013-02-11 01:37
Some messages are with a couple different:

Several of these wrapped around the Main Page, Community portal, etc. links:
Notice: Undefined variable: options in /usr/local/apache2/htdocs/wiki/skins/strapping/Strapping.php on line 221

One of these in the upper-right near the username:
Notice: Undefined variable: theImg in /usr/local/apache2/htdocs/wiki/skins/strapping/Strapping.php on line 662

And one of these at the bottom of the page above the footer:
Warning: Missing argument 1 for StrappingTemplate::renderPortals(), called in /usr/local/apache2/htdocs/wiki/skins/strapping/Strapping.php on line 335 and defined in /usr/local/apache2/htdocs/wiki/skins/strapping/Strapping.php on line 406

**Comment by Arcane21** [comment] 2013-02-11 03:54
I'm running my wiki as a localhost, but I get the same messages.

Date: Sun, 10 Feb 2013 17:37:16 -0800

**Comment by AlJohnson** [comment] 2013-02-25 12:48
Please fix this b/c these skins are bad-ass but I can't use if broken. Thanks!

**Comment by garrett** [comment] 2013-02-25 15:01
Hi,

Sorry — I was sick with the flu for a few weeks. Last week, I was just getting back to work and have a backlog of stuff to do and an upcoming major project due in around a month. I'll try to get it fixed when I can.

Meanwhile, if someone fixes this specificall, I can merge in a fix.

(It might be fixed in the pull request already — I simply haven't had the time to set up my test server again and check it out yet. I will _definitely_ do this sometime in the next week or two.)

**Comment by garrett** [comment] 2013-03-15 09:19
I've merged in pull request #9 and dropdowns definitely work for me in my MediaWiki development instance.

Please test with the new version and let me know if it fixes these issues for you.

**Comment by Arcane21** [comment] 2013-03-15 11:02
Well, it seems the drop down menus function more or less as they should [the print/export menu reports an "invalid argument foreach () error on line 645 of strapping.skin.php, but everything else is fine.]

I do have to admit I probably wouldn't use this as my default skin,but I would say that aside from the above mentioned error, most of the important technical issues seem to have been resolved.

**Comment by AlJohnson** [comment] 2013-03-15 22:01
Hi Garrett,

I just installed with the new readme instructions (removed those links) and all I get is a basic Vector theme except with all content in one column (main content flows after the sidebar).  I placed the strapping include command above all strapping references in LocalSettings.php.

**Comment by garrett** [comment] 2013-03-16 10:59
@AlJohnson: Can you open a new issue with this? Strapping should look quite different from a Vector theme. I followed the instructions in the README at the end of the workweek and everything worked fine for me, so I can confirm it works here. Please include the version of MediaWiki and PHP that you're using and any other relevant details.

It might be related to some of the changes merged in through pull requests, but I haven't seen many problems with that. There were a couple of broken things. Most of the ones I've seen so far, I fixed yesterday. A lot of the merged-in commits fixed problems like this particular bug (and most of the issues were some basic cosmetic ones and are now fixed).

(This issue, #7 - "navbar dropdowns don't drop down", **should** be resolved, but I've been leaving it open as I hadn't had a chance to check the logs on my development site yet.)

The one still-open bug as a result of the merge (at least the only one I'm aware of so far) that affects actual usage is only #13, where sign in / create account is not displayed. (It's a little harder to track down.)

As I am already pretty busy with scheduled plans for this weekend, I won't be able to attend to fixing that particular bug until Monday — but I am definitely fixing the "sign in / create account" bug (#13) on Monday (and any others I can find or that have been reported).

@AlJohnson: Thanks in advance for filing a new bug with details of your MW and PHP versions!

**Comment by garrett** [comment] 2013-03-18 15:43
Okay, I'm closing this as WFM (works for me) with the latest changes. Please re-open if it doesn't work for you for any reason.

**Closed as completed by garrett** 2013-03-18 15:43 UTC

**Comment by AlJohnson** [comment] 2013-03-18 22:08
Hi Garrett,

I hope you had a good weekend.  It looks like this issue is resolved for FF, Opera, and IE afterall!  The problem from 3 days ago is only with Chrome.  There are some other issues too like some main menu items being repeated 3 times.  I will submit some issues for these.  Thanks!

**Comment by AlJohnson** [comment] 2013-03-19 00:26
Never mind about the repeated menu items.
